<?php

return [
    'highload_blocks' => [
        'specializations' => [
            'cardiology' => [
                'UF_NAME' => 'Кардиология',
                'UF_ACTIVE' => 1,
                'UF_SORT' => 100,
            ],
            'neurology' => [
                'UF_NAME' => 'Неврология',
                'UF_ACTIVE' => 1,
                'UF_SORT' => 200,
            ],
            'therapy' => [
                'UF_NAME' => 'Терапия',
                'UF_ACTIVE' => 1,
                'UF_SORT' => 300,
            ],
        ],
        'appointment_types' => [
            'clinic' => [
                'UF_NAME' => 'В клинике',
                'UF_ACTIVE' => 1,
                'UF_SORT' => 100,
            ],
            'online' => [
                'UF_NAME' => 'Онлайн',
                'UF_ACTIVE' => 1,
                'UF_SORT' => 200,
            ],
            'home' => [
                'UF_NAME' => 'На дому',
                'UF_ACTIVE' => 1,
                'UF_SORT' => 300,
            ],
        ],
        'locations' => [
            'central-clinic' => [
                'UF_NAME' => 'Центральная клиника',
                'UF_ADDRESS' => 'Москва, ул. Профсоюзная, д. 18',
                'UF_ACTIVE' => 1,
                'UF_SORT' => 100,
            ],
            'north-branch' => [
                'UF_NAME' => 'Северный филиал',
                'UF_ADDRESS' => 'Москва, Ленинградский пр-т, д. 47',
                'UF_ACTIVE' => 1,
                'UF_SORT' => 200,
            ],
        ],
        'services' => [
            'initial-consultation' => [
                'UF_NAME' => 'Первичная консультация',
                'UF_DESCRIPTION' => 'Первичный прием врача с осмотром и назначениями.',
                'UF_ACTIVE' => 1,
                'UF_SORT' => 100,
            ],
            'follow-up-consultation' => [
                'UF_NAME' => 'Повторная консультация',
                'UF_DESCRIPTION' => 'Повторный прием для контроля лечения.',
                'UF_ACTIVE' => 1,
                'UF_SORT' => 200,
            ],
            'ecg-interpretation' => [
                'UF_NAME' => 'Расшифровка ЭКГ',
                'UF_DESCRIPTION' => 'Консультация по результатам ЭКГ.',
                'UF_ACTIVE' => 1,
                'UF_SORT' => 300,
            ],
            'neurological-checkup' => [
                'UF_NAME' => 'Неврологический осмотр',
                'UF_DESCRIPTION' => 'Осмотр с оценкой неврологического статуса.',
                'UF_ACTIVE' => 1,
                'UF_SORT' => 400,
            ],
            'home-visit' => [
                'UF_NAME' => 'Выезд врача на дом',
                'UF_DESCRIPTION' => 'Прием врача с выездом по адресу пациента.',
                'UF_ACTIVE' => 1,
                'UF_SORT' => 500,
            ],
        ],
        'doctors' => [
            'ivanov-ii' => [
                'UF_NAME' => 'Иванов Иван Иванович',
                'UF_ACTIVE' => 1,
                'UF_SORT' => 100,
                'UF_SPECIALIZATIONS' => [
                    'cardiology',
                    'therapy',
                ],
            ],
            'petrova-aa' => [
                'UF_NAME' => 'Петрова Анна Александровна',
                'UF_ACTIVE' => 1,
                'UF_SORT' => 200,
                'UF_SPECIALIZATIONS' => [
                    'neurology',
                ],
            ],
            'sidorov-mp' => [
                'UF_NAME' => 'Сидоров Михаил Павлович',
                'UF_ACTIVE' => 1,
                'UF_SORT' => 300,
                'UF_SPECIALIZATIONS' => [
                    'therapy',
                ],
            ],
        ],
    ],
    'tables' => [
        'sklyar_ds_schedule_rule' => [
            [
                'doctor_code' => 'ivanov-ii',
                'weekday' => 1,
                'time_from_minutes' => 540,
                'time_to_minutes' => 1020,
                'active' => 'Y',
                'sort' => 100,
                'created_at' => '2025-01-10 09:00:00',
                'updated_at' => null,
            ],
            [
                'doctor_code' => 'ivanov-ii',
                'weekday' => 3,
                'time_from_minutes' => 600,
                'time_to_minutes' => 1080,
                'active' => 'Y',
                'sort' => 200,
                'created_at' => '2025-01-10 09:00:00',
                'updated_at' => null,
            ],
            [
                'doctor_code' => 'ivanov-ii',
                'weekday' => 5,
                'time_from_minutes' => 540,
                'time_to_minutes' => 960,
                'active' => 'Y',
                'sort' => 300,
                'created_at' => '2025-01-10 09:00:00',
                'updated_at' => null,
            ],
            [
                'doctor_code' => 'petrova-aa',
                'weekday' => 2,
                'time_from_minutes' => 600,
                'time_to_minutes' => 1080,
                'active' => 'Y',
                'sort' => 100,
                'created_at' => '2025-01-10 09:05:00',
                'updated_at' => null,
            ],
            [
                'doctor_code' => 'petrova-aa',
                'weekday' => 4,
                'time_from_minutes' => 600,
                'time_to_minutes' => 1080,
                'active' => 'Y',
                'sort' => 200,
                'created_at' => '2025-01-10 09:05:00',
                'updated_at' => null,
            ],
            [
                'doctor_code' => 'petrova-aa',
                'weekday' => 6,
                'time_from_minutes' => 660,
                'time_to_minutes' => 900,
                'active' => 'Y',
                'sort' => 300,
                'created_at' => '2025-01-10 09:05:00',
                'updated_at' => null,
            ],
            [
                'doctor_code' => 'sidorov-mp',
                'weekday' => 1,
                'time_from_minutes' => 480,
                'time_to_minutes' => 900,
                'active' => 'Y',
                'sort' => 100,
                'created_at' => '2025-01-10 09:10:00',
                'updated_at' => null,
            ],
            [
                'doctor_code' => 'sidorov-mp',
                'weekday' => 2,
                'time_from_minutes' => 480,
                'time_to_minutes' => 900,
                'active' => 'Y',
                'sort' => 200,
                'created_at' => '2025-01-10 09:10:00',
                'updated_at' => null,
            ],
            [
                'doctor_code' => 'sidorov-mp',
                'weekday' => 4,
                'time_from_minutes' => 720,
                'time_to_minutes' => 1140,
                'active' => 'Y',
                'sort' => 300,
                'created_at' => '2025-01-10 09:10:00',
                'updated_at' => null,
            ],
        ],
        'sklyar_ds_service_price' => [
            'ivanov-initial-clinic-central' => [
                'doctor_code' => 'ivanov-ii',
                'service_code' => 'initial-consultation',
                'appointment_type_code' => 'clinic',
                'location_code' => 'central-clinic',
                'price' => '2500.00',
                'currency' => 'RUB',
                'duration_minutes' => 30,
                'active' => 'Y',
                'sort' => 100,
                'created_at' => '2025-01-10 09:15:00',
                'updated_at' => null,
            ],
            'ivanov-follow-up-online' => [
                'doctor_code' => 'ivanov-ii',
                'service_code' => 'follow-up-consultation',
                'appointment_type_code' => 'online',
                'location_code' => null,
                'price' => '1800.00',
                'currency' => 'RUB',
                'duration_minutes' => 20,
                'active' => 'Y',
                'sort' => 200,
                'created_at' => '2025-01-10 09:15:00',
                'updated_at' => null,
            ],
            'petrova-neuro-clinic-north' => [
                'doctor_code' => 'petrova-aa',
                'service_code' => 'neurological-checkup',
                'appointment_type_code' => 'clinic',
                'location_code' => 'north-branch',
                'price' => '3200.00',
                'currency' => 'RUB',
                'duration_minutes' => 40,
                'active' => 'Y',
                'sort' => 100,
                'created_at' => '2025-01-10 09:20:00',
                'updated_at' => null,
            ],
            'petrova-follow-up-online' => [
                'doctor_code' => 'petrova-aa',
                'service_code' => 'follow-up-consultation',
                'appointment_type_code' => 'online',
                'location_code' => null,
                'price' => '2100.00',
                'currency' => 'RUB',
                'duration_minutes' => 30,
                'active' => 'Y',
                'sort' => 200,
                'created_at' => '2025-01-10 09:20:00',
                'updated_at' => null,
            ],
            'sidorov-initial-home' => [
                'doctor_code' => 'sidorov-mp',
                'service_code' => 'home-visit',
                'appointment_type_code' => 'home',
                'location_code' => null,
                'price' => '4500.00',
                'currency' => 'RUB',
                'duration_minutes' => 60,
                'active' => 'Y',
                'sort' => 100,
                'created_at' => '2025-01-10 09:25:00',
                'updated_at' => null,
            ],
            'sidorov-ecg-clinic-central' => [
                'doctor_code' => 'sidorov-mp',
                'service_code' => 'ecg-interpretation',
                'appointment_type_code' => 'clinic',
                'location_code' => 'central-clinic',
                'price' => '1700.00',
                'currency' => 'RUB',
                'duration_minutes' => 20,
                'active' => 'Y',
                'sort' => 200,
                'created_at' => '2025-01-10 09:25:00',
                'updated_at' => null,
            ],
        ],
        'sklyar_ds_booking' => [
            [
                'service_price_code' => 'ivanov-initial-clinic-central',
                'doctor_code' => 'ivanov-ii',
                'service_code' => 'initial-consultation',
                'appointment_type_code' => 'clinic',
                'location_code' => 'central-clinic',
                'booking_date' => '2025-01-20',
                'time_from_minutes' => 600,
                'time_to_minutes' => 630,
                'patient_name' => 'Орлов Сергей Викторович',
                'patient_phone' => '+7 999 111-22-33',
                'patient_email' => 'orlov@example.test',
                'patient_comment' => 'Беспокоит давление и учащенное сердцебиение.',
                'visit_address' => null,
                'online_link' => null,
                'price_snapshot' => '2500.00',
                'currency_snapshot' => 'RUB',
                'doctor_name_snapshot' => 'Иванов Иван Иванович',
                'service_name_snapshot' => 'Первичная консультация',
                'appointment_type_name_snapshot' => 'В клинике',
                'location_name_snapshot' => 'Центральная клиника',
                'status' => 'new',
                'created_at' => '2025-01-15 11:00:00',
                'updated_at' => null,
            ],
            [
                'service_price_code' => 'ivanov-follow-up-online',
                'doctor_code' => 'ivanov-ii',
                'service_code' => 'follow-up-consultation',
                'appointment_type_code' => 'online',
                'location_code' => null,
                'booking_date' => '2025-01-21',
                'time_from_minutes' => 780,
                'time_to_minutes' => 800,
                'patient_name' => 'Кузнецова Мария Олеговна',
                'patient_phone' => '+7 999 222-33-44',
                'patient_email' => 'kuznetsova@example.test',
                'patient_comment' => 'Нужна онлайн-консультация по результатам анализов.',
                'visit_address' => null,
                'online_link' => 'https://example.test/meeting/ivanov-follow-up',
                'price_snapshot' => '1800.00',
                'currency_snapshot' => 'RUB',
                'doctor_name_snapshot' => 'Иванов Иван Иванович',
                'service_name_snapshot' => 'Повторная консультация',
                'appointment_type_name_snapshot' => 'Онлайн',
                'location_name_snapshot' => null,
                'status' => 'confirmed',
                'created_at' => '2025-01-16 14:20:00',
                'updated_at' => '2025-01-16 14:45:00',
            ],
            [
                'service_price_code' => 'petrova-neuro-clinic-north',
                'doctor_code' => 'petrova-aa',
                'service_code' => 'neurological-checkup',
                'appointment_type_code' => 'clinic',
                'location_code' => 'north-branch',
                'booking_date' => '2025-01-22',
                'time_from_minutes' => 660,
                'time_to_minutes' => 700,
                'patient_name' => 'Васильев Артем Игоревич',
                'patient_phone' => '+7 999 333-44-55',
                'patient_email' => null,
                'patient_comment' => 'Частые головные боли и головокружение.',
                'visit_address' => null,
                'online_link' => null,
                'price_snapshot' => '3200.00',
                'currency_snapshot' => 'RUB',
                'doctor_name_snapshot' => 'Петрова Анна Александровна',
                'service_name_snapshot' => 'Неврологический осмотр',
                'appointment_type_name_snapshot' => 'В клинике',
                'location_name_snapshot' => 'Северный филиал',
                'status' => 'new',
                'created_at' => '2025-01-17 09:30:00',
                'updated_at' => null,
            ],
            [
                'service_price_code' => 'sidorov-initial-home',
                'doctor_code' => 'sidorov-mp',
                'service_code' => 'home-visit',
                'appointment_type_code' => 'home',
                'location_code' => null,
                'booking_date' => '2025-01-23',
                'time_from_minutes' => 840,
                'time_to_minutes' => 900,
                'patient_name' => 'Егорова Светлана Петровна',
                'patient_phone' => '+7 999 444-55-66',
                'patient_email' => 'egorova@example.test',
                'patient_comment' => 'Высокая температура, нужен осмотр на дому.',
                'visit_address' => 'Москва, ул. Вавилова, д. 27, кв. 14',
                'online_link' => null,
                'price_snapshot' => '4500.00',
                'currency_snapshot' => 'RUB',
                'doctor_name_snapshot' => 'Сидоров Михаил Павлович',
                'service_name_snapshot' => 'Выезд врача на дом',
                'appointment_type_name_snapshot' => 'На дому',
                'location_name_snapshot' => null,
                'status' => 'confirmed',
                'created_at' => '2025-01-18 12:10:00',
                'updated_at' => '2025-01-18 12:30:00',
            ],
        ],
    ],
];
